/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as DisplayLeaderboardRouteImport } from './routes/display.leaderboard'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthNoAccessRouteImport } from './routes/_auth.no-access'
import { Route as AuthMyRatingRouteImport } from './routes/_auth.my-rating'
import { Route as AuthMyContractsRouteImport } from './routes/_auth.my-contracts'
import { Route as AuthInfoRouteImport } from './routes/_auth.info'
import { Route as AuthCompareRouteImport } from './routes/_auth.compare'
import { Route as AuthCompanyRouteImport } from './routes/_auth.company'
import { Route as AuthChangePasswordRouteImport } from './routes/_auth.change-password'
import { Route as AuthAdmireRouteImport } from './routes/_auth.admire'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as AuthCompanyIndexRouteImport } from './routes/_auth.company.index'
import { Route as AuthInfoRatingsRouteImport } from './routes/_auth.info.ratings'
import { Route as AuthInfoOscarsRouteImport } from './routes/_auth.info.oscars'
import { Route as AuthInfoFilmsRouteImport } from './routes/_auth.info.films'
import { Route as AuthInfoContractsHistoryRouteImport } from './routes/_auth.info.contracts-history'
import { Route as AuthCompanyRatingRouteImport } from './routes/_auth.company.rating'
import { Route as AuthCompanyOscarNominationsRouteImport } from './routes/_auth.company.oscar-nominations'
import { Route as AuthCompanyFilmsRouteImport } from './routes/_auth.company.films'
import { Route as AuthCompanyDocumentsRouteImport } from './routes/_auth.company.documents'
import { Route as AuthCompanyContractsRouteImport } from './routes/_auth.company.contracts'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth.admin.users'
import { Route as AuthAdminTransactionsRouteImport } from './routes/_auth.admin.transactions'
import { Route as AuthAdminRandomizerRouteImport } from './routes/_auth.admin.randomizer'
import { Route as AuthAdminOscarsRouteImport } from './routes/_auth.admin.oscars'
import { Route as AuthAdminFilmsRouteImport } from './routes/_auth.admin.films'
import { Route as AuthAdminDefaultScansRouteImport } from './routes/_auth.admin.default-scans'
import { Route as AuthAdminContractsRouteImport } from './routes/_auth.admin.contracts'
import { Route as AuthAdminCompaniesRouteImport } from './routes/_auth.admin.companies'
import { Route as AuthAdminPersonsIndexRouteImport } from './routes/_auth.admin.persons.index'
import { Route as AuthAdminJobsIndexRouteImport } from './routes/_auth.admin.jobs.index'
import { Route as AuthAdminPersonsIdRouteImport } from './routes/_auth.admin.persons.$id'
import { Route as AuthAdminJobsKeyRouteImport } from './routes/_auth.admin.jobs.$key'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DisplayLeaderboardRoute = DisplayLeaderboardRouteImport.update({
  id: '/display/leaderboard',
  path: '/display/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNoAccessRoute = AuthNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMyRatingRoute = AuthMyRatingRouteImport.update({
  id: '/my-rating',
  path: '/my-rating',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMyContractsRoute = AuthMyContractsRouteImport.update({
  id: '/my-contracts',
  path: '/my-contracts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInfoRoute = AuthInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompareRoute = AuthCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompanyRoute = AuthCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdmireRoute = AuthAdmireRouteImport.update({
  id: '/admire',
  path: '/admire',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompanyIndexRoute = AuthCompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthCompanyRoute,
} as any)
const AuthInfoRatingsRoute = AuthInfoRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AuthInfoRoute,
} as any)
const AuthInfoOscarsRoute = AuthInfoOscarsRouteImport.update({
  id: '/oscars',
  path: '/oscars',
  getParentRoute: () => AuthInfoRoute,
} as any)
const AuthInfoFilmsRoute = AuthInfoFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => AuthInfoRoute,
} as any)
const AuthInfoContractsHistoryRoute =
  AuthInfoContractsHistoryRouteImport.update({
    id: '/contracts-history',
    path: '/contracts-history',
    getParentRoute: () => AuthInfoRoute,
  } as any)
const AuthCompanyRatingRoute = AuthCompanyRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => AuthCompanyRoute,
} as any)
const AuthCompanyOscarNominationsRoute =
  AuthCompanyOscarNominationsRouteImport.update({
    id: '/oscar-nominations',
    path: '/oscar-nominations',
    getParentRoute: () => AuthCompanyRoute,
  } as any)
const AuthCompanyFilmsRoute = AuthCompanyFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => AuthCompanyRoute,
} as any)
const AuthCompanyDocumentsRoute = AuthCompanyDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthCompanyRoute,
} as any)
const AuthCompanyContractsRoute = AuthCompanyContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthCompanyRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminTransactionsRoute = AuthAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminRandomizerRoute = AuthAdminRandomizerRouteImport.update({
  id: '/randomizer',
  path: '/randomizer',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminOscarsRoute = AuthAdminOscarsRouteImport.update({
  id: '/oscars',
  path: '/oscars',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminFilmsRoute = AuthAdminFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminDefaultScansRoute = AuthAdminDefaultScansRouteImport.update({
  id: '/default-scans',
  path: '/default-scans',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminContractsRoute = AuthAdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminCompaniesRoute = AuthAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminPersonsIndexRoute = AuthAdminPersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminJobsIndexRoute = AuthAdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminPersonsIdRoute = AuthAdminPersonsIdRouteImport.update({
  id: '/persons/$id',
  path: '/persons/$id',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminJobsKeyRoute = AuthAdminJobsKeyRouteImport.update({
  id: '/jobs/$key',
  path: '/jobs/$key',
  getParentRoute: () => AuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/admire': typeof AuthAdmireRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/company': typeof AuthCompanyRouteWithChildren
  '/compare': typeof AuthCompareRoute
  '/info': typeof AuthInfoRouteWithChildren
  '/my-contracts': typeof AuthMyContractsRoute
  '/my-rating': typeof AuthMyRatingRoute
  '/no-access': typeof AuthNoAccessRoute
  '/profile': typeof AuthProfileRoute
  '/display/leaderboard': typeof DisplayLeaderboardRoute
  '/admin/companies': typeof AuthAdminCompaniesRoute
  '/admin/contracts': typeof AuthAdminContractsRoute
  '/admin/default-scans': typeof AuthAdminDefaultScansRoute
  '/admin/films': typeof AuthAdminFilmsRoute
  '/admin/oscars': typeof AuthAdminOscarsRoute
  '/admin/randomizer': typeof AuthAdminRandomizerRoute
  '/admin/transactions': typeof AuthAdminTransactionsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/company/contracts': typeof AuthCompanyContractsRoute
  '/company/documents': typeof AuthCompanyDocumentsRoute
  '/company/films': typeof AuthCompanyFilmsRoute
  '/company/oscar-nominations': typeof AuthCompanyOscarNominationsRoute
  '/company/rating': typeof AuthCompanyRatingRoute
  '/info/contracts-history': typeof AuthInfoContractsHistoryRoute
  '/info/films': typeof AuthInfoFilmsRoute
  '/info/oscars': typeof AuthInfoOscarsRoute
  '/info/ratings': typeof AuthInfoRatingsRoute
  '/company/': typeof AuthCompanyIndexRoute
  '/admin/jobs/$key': typeof AuthAdminJobsKeyRoute
  '/admin/persons/$id': typeof AuthAdminPersonsIdRoute
  '/admin/jobs/': typeof AuthAdminJobsIndexRoute
  '/admin/persons/': typeof AuthAdminPersonsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/admire': typeof AuthAdmireRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/compare': typeof AuthCompareRoute
  '/info': typeof AuthInfoRouteWithChildren
  '/my-contracts': typeof AuthMyContractsRoute
  '/my-rating': typeof AuthMyRatingRoute
  '/no-access': typeof AuthNoAccessRoute
  '/profile': typeof AuthProfileRoute
  '/display/leaderboard': typeof DisplayLeaderboardRoute
  '/': typeof AuthIndexRoute
  '/admin/companies': typeof AuthAdminCompaniesRoute
  '/admin/contracts': typeof AuthAdminContractsRoute
  '/admin/default-scans': typeof AuthAdminDefaultScansRoute
  '/admin/films': typeof AuthAdminFilmsRoute
  '/admin/oscars': typeof AuthAdminOscarsRoute
  '/admin/randomizer': typeof AuthAdminRandomizerRoute
  '/admin/transactions': typeof AuthAdminTransactionsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/company/contracts': typeof AuthCompanyContractsRoute
  '/company/documents': typeof AuthCompanyDocumentsRoute
  '/company/films': typeof AuthCompanyFilmsRoute
  '/company/oscar-nominations': typeof AuthCompanyOscarNominationsRoute
  '/company/rating': typeof AuthCompanyRatingRoute
  '/info/contracts-history': typeof AuthInfoContractsHistoryRoute
  '/info/films': typeof AuthInfoFilmsRoute
  '/info/oscars': typeof AuthInfoOscarsRoute
  '/info/ratings': typeof AuthInfoRatingsRoute
  '/company': typeof AuthCompanyIndexRoute
  '/admin/jobs/$key': typeof AuthAdminJobsKeyRoute
  '/admin/persons/$id': typeof AuthAdminPersonsIdRoute
  '/admin/jobs': typeof AuthAdminJobsIndexRoute
  '/admin/persons': typeof AuthAdminPersonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/admire': typeof AuthAdmireRoute
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/company': typeof AuthCompanyRouteWithChildren
  '/_auth/compare': typeof AuthCompareRoute
  '/_auth/info': typeof AuthInfoRouteWithChildren
  '/_auth/my-contracts': typeof AuthMyContractsRoute
  '/_auth/my-rating': typeof AuthMyRatingRoute
  '/_auth/no-access': typeof AuthNoAccessRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/display/leaderboard': typeof DisplayLeaderboardRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/companies': typeof AuthAdminCompaniesRoute
  '/_auth/admin/contracts': typeof AuthAdminContractsRoute
  '/_auth/admin/default-scans': typeof AuthAdminDefaultScansRoute
  '/_auth/admin/films': typeof AuthAdminFilmsRoute
  '/_auth/admin/oscars': typeof AuthAdminOscarsRoute
  '/_auth/admin/randomizer': typeof AuthAdminRandomizerRoute
  '/_auth/admin/transactions': typeof AuthAdminTransactionsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/company/contracts': typeof AuthCompanyContractsRoute
  '/_auth/company/documents': typeof AuthCompanyDocumentsRoute
  '/_auth/company/films': typeof AuthCompanyFilmsRoute
  '/_auth/company/oscar-nominations': typeof AuthCompanyOscarNominationsRoute
  '/_auth/company/rating': typeof AuthCompanyRatingRoute
  '/_auth/info/contracts-history': typeof AuthInfoContractsHistoryRoute
  '/_auth/info/films': typeof AuthInfoFilmsRoute
  '/_auth/info/oscars': typeof AuthInfoOscarsRoute
  '/_auth/info/ratings': typeof AuthInfoRatingsRoute
  '/_auth/company/': typeof AuthCompanyIndexRoute
  '/_auth/admin/jobs/$key': typeof AuthAdminJobsKeyRoute
  '/_auth/admin/persons/$id': typeof AuthAdminPersonsIdRoute
  '/_auth/admin/jobs/': typeof AuthAdminJobsIndexRoute
  '/_auth/admin/persons/': typeof AuthAdminPersonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/status'
    | '/admin'
    | '/admire'
    | '/change-password'
    | '/company'
    | '/compare'
    | '/info'
    | '/my-contracts'
    | '/my-rating'
    | '/no-access'
    | '/profile'
    | '/display/leaderboard'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/default-scans'
    | '/admin/films'
    | '/admin/oscars'
    | '/admin/randomizer'
    | '/admin/transactions'
    | '/admin/users'
    | '/company/contracts'
    | '/company/documents'
    | '/company/films'
    | '/company/oscar-nominations'
    | '/company/rating'
    | '/info/contracts-history'
    | '/info/films'
    | '/info/oscars'
    | '/info/ratings'
    | '/company/'
    | '/admin/jobs/$key'
    | '/admin/persons/$id'
    | '/admin/jobs/'
    | '/admin/persons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/status'
    | '/admin'
    | '/admire'
    | '/change-password'
    | '/compare'
    | '/info'
    | '/my-contracts'
    | '/my-rating'
    | '/no-access'
    | '/profile'
    | '/display/leaderboard'
    | '/'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/default-scans'
    | '/admin/films'
    | '/admin/oscars'
    | '/admin/randomizer'
    | '/admin/transactions'
    | '/admin/users'
    | '/company/contracts'
    | '/company/documents'
    | '/company/films'
    | '/company/oscar-nominations'
    | '/company/rating'
    | '/info/contracts-history'
    | '/info/films'
    | '/info/oscars'
    | '/info/ratings'
    | '/company'
    | '/admin/jobs/$key'
    | '/admin/persons/$id'
    | '/admin/jobs'
    | '/admin/persons'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/status'
    | '/_auth/admin'
    | '/_auth/admire'
    | '/_auth/change-password'
    | '/_auth/company'
    | '/_auth/compare'
    | '/_auth/info'
    | '/_auth/my-contracts'
    | '/_auth/my-rating'
    | '/_auth/no-access'
    | '/_auth/profile'
    | '/display/leaderboard'
    | '/_auth/'
    | '/_auth/admin/companies'
    | '/_auth/admin/contracts'
    | '/_auth/admin/default-scans'
    | '/_auth/admin/films'
    | '/_auth/admin/oscars'
    | '/_auth/admin/randomizer'
    | '/_auth/admin/transactions'
    | '/_auth/admin/users'
    | '/_auth/company/contracts'
    | '/_auth/company/documents'
    | '/_auth/company/films'
    | '/_auth/company/oscar-nominations'
    | '/_auth/company/rating'
    | '/_auth/info/contracts-history'
    | '/_auth/info/films'
    | '/_auth/info/oscars'
    | '/_auth/info/ratings'
    | '/_auth/company/'
    | '/_auth/admin/jobs/$key'
    | '/_auth/admin/persons/$id'
    | '/_auth/admin/jobs/'
    | '/_auth/admin/persons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  StatusRoute: typeof StatusRoute
  DisplayLeaderboardRoute: typeof DisplayLeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/display/leaderboard': {
      id: '/display/leaderboard'
      path: '/display/leaderboard'
      fullPath: '/display/leaderboard'
      preLoaderRoute: typeof DisplayLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/no-access': {
      id: '/_auth/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AuthNoAccessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/my-rating': {
      id: '/_auth/my-rating'
      path: '/my-rating'
      fullPath: '/my-rating'
      preLoaderRoute: typeof AuthMyRatingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/my-contracts': {
      id: '/_auth/my-contracts'
      path: '/my-contracts'
      fullPath: '/my-contracts'
      preLoaderRoute: typeof AuthMyContractsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/info': {
      id: '/_auth/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof AuthInfoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/compare': {
      id: '/_auth/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthCompareRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/company': {
      id: '/_auth/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthCompanyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admire': {
      id: '/_auth/admire'
      path: '/admire'
      fullPath: '/admire'
      preLoaderRoute: typeof AuthAdmireRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/company/': {
      id: '/_auth/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof AuthCompanyIndexRouteImport
      parentRoute: typeof AuthCompanyRoute
    }
    '/_auth/info/ratings': {
      id: '/_auth/info/ratings'
      path: '/ratings'
      fullPath: '/info/ratings'
      preLoaderRoute: typeof AuthInfoRatingsRouteImport
      parentRoute: typeof AuthInfoRoute
    }
    '/_auth/info/oscars': {
      id: '/_auth/info/oscars'
      path: '/oscars'
      fullPath: '/info/oscars'
      preLoaderRoute: typeof AuthInfoOscarsRouteImport
      parentRoute: typeof AuthInfoRoute
    }
    '/_auth/info/films': {
      id: '/_auth/info/films'
      path: '/films'
      fullPath: '/info/films'
      preLoaderRoute: typeof AuthInfoFilmsRouteImport
      parentRoute: typeof AuthInfoRoute
    }
    '/_auth/info/contracts-history': {
      id: '/_auth/info/contracts-history'
      path: '/contracts-history'
      fullPath: '/info/contracts-history'
      preLoaderRoute: typeof AuthInfoContractsHistoryRouteImport
      parentRoute: typeof AuthInfoRoute
    }
    '/_auth/company/rating': {
      id: '/_auth/company/rating'
      path: '/rating'
      fullPath: '/company/rating'
      preLoaderRoute: typeof AuthCompanyRatingRouteImport
      parentRoute: typeof AuthCompanyRoute
    }
    '/_auth/company/oscar-nominations': {
      id: '/_auth/company/oscar-nominations'
      path: '/oscar-nominations'
      fullPath: '/company/oscar-nominations'
      preLoaderRoute: typeof AuthCompanyOscarNominationsRouteImport
      parentRoute: typeof AuthCompanyRoute
    }
    '/_auth/company/films': {
      id: '/_auth/company/films'
      path: '/films'
      fullPath: '/company/films'
      preLoaderRoute: typeof AuthCompanyFilmsRouteImport
      parentRoute: typeof AuthCompanyRoute
    }
    '/_auth/company/documents': {
      id: '/_auth/company/documents'
      path: '/documents'
      fullPath: '/company/documents'
      preLoaderRoute: typeof AuthCompanyDocumentsRouteImport
      parentRoute: typeof AuthCompanyRoute
    }
    '/_auth/company/contracts': {
      id: '/_auth/company/contracts'
      path: '/contracts'
      fullPath: '/company/contracts'
      preLoaderRoute: typeof AuthCompanyContractsRouteImport
      parentRoute: typeof AuthCompanyRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/transactions': {
      id: '/_auth/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthAdminTransactionsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/randomizer': {
      id: '/_auth/admin/randomizer'
      path: '/randomizer'
      fullPath: '/admin/randomizer'
      preLoaderRoute: typeof AuthAdminRandomizerRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/oscars': {
      id: '/_auth/admin/oscars'
      path: '/oscars'
      fullPath: '/admin/oscars'
      preLoaderRoute: typeof AuthAdminOscarsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/films': {
      id: '/_auth/admin/films'
      path: '/films'
      fullPath: '/admin/films'
      preLoaderRoute: typeof AuthAdminFilmsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/default-scans': {
      id: '/_auth/admin/default-scans'
      path: '/default-scans'
      fullPath: '/admin/default-scans'
      preLoaderRoute: typeof AuthAdminDefaultScansRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/contracts': {
      id: '/_auth/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthAdminContractsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/companies': {
      id: '/_auth/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthAdminCompaniesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/persons/': {
      id: '/_auth/admin/persons/'
      path: '/persons'
      fullPath: '/admin/persons/'
      preLoaderRoute: typeof AuthAdminPersonsIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/jobs/': {
      id: '/_auth/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthAdminJobsIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/persons/$id': {
      id: '/_auth/admin/persons/$id'
      path: '/persons/$id'
      fullPath: '/admin/persons/$id'
      preLoaderRoute: typeof AuthAdminPersonsIdRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/jobs/$key': {
      id: '/_auth/admin/jobs/$key'
      path: '/jobs/$key'
      fullPath: '/admin/jobs/$key'
      preLoaderRoute: typeof AuthAdminJobsKeyRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminCompaniesRoute: typeof AuthAdminCompaniesRoute
  AuthAdminContractsRoute: typeof AuthAdminContractsRoute
  AuthAdminDefaultScansRoute: typeof AuthAdminDefaultScansRoute
  AuthAdminFilmsRoute: typeof AuthAdminFilmsRoute
  AuthAdminOscarsRoute: typeof AuthAdminOscarsRoute
  AuthAdminRandomizerRoute: typeof AuthAdminRandomizerRoute
  AuthAdminTransactionsRoute: typeof AuthAdminTransactionsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminJobsKeyRoute: typeof AuthAdminJobsKeyRoute
  AuthAdminPersonsIdRoute: typeof AuthAdminPersonsIdRoute
  AuthAdminJobsIndexRoute: typeof AuthAdminJobsIndexRoute
  AuthAdminPersonsIndexRoute: typeof AuthAdminPersonsIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminCompaniesRoute: AuthAdminCompaniesRoute,
  AuthAdminContractsRoute: AuthAdminContractsRoute,
  AuthAdminDefaultScansRoute: AuthAdminDefaultScansRoute,
  AuthAdminFilmsRoute: AuthAdminFilmsRoute,
  AuthAdminOscarsRoute: AuthAdminOscarsRoute,
  AuthAdminRandomizerRoute: AuthAdminRandomizerRoute,
  AuthAdminTransactionsRoute: AuthAdminTransactionsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminJobsKeyRoute: AuthAdminJobsKeyRoute,
  AuthAdminPersonsIdRoute: AuthAdminPersonsIdRoute,
  AuthAdminJobsIndexRoute: AuthAdminJobsIndexRoute,
  AuthAdminPersonsIndexRoute: AuthAdminPersonsIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthCompanyRouteChildren {
  AuthCompanyContractsRoute: typeof AuthCompanyContractsRoute
  AuthCompanyDocumentsRoute: typeof AuthCompanyDocumentsRoute
  AuthCompanyFilmsRoute: typeof AuthCompanyFilmsRoute
  AuthCompanyOscarNominationsRoute: typeof AuthCompanyOscarNominationsRoute
  AuthCompanyRatingRoute: typeof AuthCompanyRatingRoute
  AuthCompanyIndexRoute: typeof AuthCompanyIndexRoute
}

const AuthCompanyRouteChildren: AuthCompanyRouteChildren = {
  AuthCompanyContractsRoute: AuthCompanyContractsRoute,
  AuthCompanyDocumentsRoute: AuthCompanyDocumentsRoute,
  AuthCompanyFilmsRoute: AuthCompanyFilmsRoute,
  AuthCompanyOscarNominationsRoute: AuthCompanyOscarNominationsRoute,
  AuthCompanyRatingRoute: AuthCompanyRatingRoute,
  AuthCompanyIndexRoute: AuthCompanyIndexRoute,
}

const AuthCompanyRouteWithChildren = AuthCompanyRoute._addFileChildren(
  AuthCompanyRouteChildren,
)

interface AuthInfoRouteChildren {
  AuthInfoContractsHistoryRoute: typeof AuthInfoContractsHistoryRoute
  AuthInfoFilmsRoute: typeof AuthInfoFilmsRoute
  AuthInfoOscarsRoute: typeof AuthInfoOscarsRoute
  AuthInfoRatingsRoute: typeof AuthInfoRatingsRoute
}

const AuthInfoRouteChildren: AuthInfoRouteChildren = {
  AuthInfoContractsHistoryRoute: AuthInfoContractsHistoryRoute,
  AuthInfoFilmsRoute: AuthInfoFilmsRoute,
  AuthInfoOscarsRoute: AuthInfoOscarsRoute,
  AuthInfoRatingsRoute: AuthInfoRatingsRoute,
}

const AuthInfoRouteWithChildren = AuthInfoRoute._addFileChildren(
  AuthInfoRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthAdmireRoute: typeof AuthAdmireRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthCompanyRoute: typeof AuthCompanyRouteWithChildren
  AuthCompareRoute: typeof AuthCompareRoute
  AuthInfoRoute: typeof AuthInfoRouteWithChildren
  AuthMyContractsRoute: typeof AuthMyContractsRoute
  AuthMyRatingRoute: typeof AuthMyRatingRoute
  AuthNoAccessRoute: typeof AuthNoAccessRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthAdmireRoute: AuthAdmireRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthCompanyRoute: AuthCompanyRouteWithChildren,
  AuthCompareRoute: AuthCompareRoute,
  AuthInfoRoute: AuthInfoRouteWithChildren,
  AuthMyContractsRoute: AuthMyContractsRoute,
  AuthMyRatingRoute: AuthMyRatingRoute,
  AuthNoAccessRoute: AuthNoAccessRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  StatusRoute: StatusRoute,
  DisplayLeaderboardRoute: DisplayLeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
